config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :contacts, only: [:index, :destroy] do
    collection do
      resources :imports, only: [:new, :create, :show], path: 'import'
    end
  end

  get 'contacts/*path' => 'contacts#index'
  post 'imports/:id/confirm' => 'imports#confirm'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactReact</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://js.pusher.com/3.2/pusher.min.js" %>

    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>

    <nav>
      <div class="nav-wrapper">
        <div class="container">
        <div class="row">
          <a href="/" class="brand-logo">ContactReact <label>by @rossta</label></a>
          <ul id="nav-mobile" class="right">
            <% if current_page?(controller: "welcome", action: "index") %>
              <li><%= link_to "Go to Dashboard", contacts_path %></li>
            <% else %>
              <li><%= link_to "Contacts", contacts_path %></li>
            <% end %>
          </ul>
        </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <main>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

  </body>
</html>